;/*FB_PKG_DELIM*/

__d("Deferred",["Promise"],(function(a,b,c,d,e,f){"use strict";var g;(g||(g=b("Promise"))).resolve();a=function(){function a(a){var c=this;a=a||g||(g=b("Promise"));this.$1=!1;this.$2=new a(function(a,b){c.$3=a,c.$4=b})}var c=a.prototype;c.getPromise=function(){return this.$2};c.resolve=function(a){this.$1=!0,this.$3(a)};c.reject=function(a){this.$1=!0,this.$4(a)};c.isSettled=function(){return this.$1};return a}();f["default"]=a}),66);
__d("isHorizonDotMetaDotComURI",[],(function(a,b,c,d,e,f){var g=new RegExp("(^|\\.)horizon\\.meta\\.com$","i"),h=["https"];function a(a){if(a.isEmpty()&&a.toString()!=="#")return!1;return!a.getDomain()&&!a.getProtocol()?!1:h.indexOf(a.getProtocol())!==-1&&g.test(a.getDomain())}f["default"]=a}),66);
__d("isWorkDotMetaDotComURI",[],(function(a,b,c,d,e,f){var g=new RegExp("(^|\\.)work\\.meta\\.com$","i"),h=["https"];function a(a){if(a.isEmpty()&&a.toString()!=="#")return!1;return!a.getDomain()&&!a.getProtocol()?!1:h.indexOf(a.getProtocol())!==-1&&g.test(a.getDomain())}f["default"]=a}),66);
__d("isWorkroomsDotComURI",[],(function(a,b,c,d,e,f){var g=new RegExp("(^|\\.)workrooms\\.com$","i"),h=["https"];function a(a){if(a.isEmpty()&&a.toString()!=="#")return!1;return!a.getDomain()&&!a.getProtocol()?!1:h.indexOf(a.getProtocol())!==-1&&g.test(a.getDomain())}f["default"]=a}),66);
__d("Qe2JsExposureFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1837559");b=d("FalcoLoggerInternal").create("qe2_js_exposure",a);e=b;g["default"]=e}),98);
__d("QE2Logger",["Qe2JsExposureFalcoEvent"],(function(a,b,c,d,e,f,g){"use strict";var h={};function a(a,b){F(a,(a=b)!=null?a:"",9)}function b(a,b){F(a,(a=b)!=null?a:"",9,null,"immediate")}function d(a){F(a,"",32)}function e(a){F(a,"",32,null,"immediate")}function f(a){F(a,"",54)}function i(a,b){F(a,"",54,b,"immediate")}function j(a,b){F(a,"",54,b,"critical")}function k(a,b){F(a,b,3)}function l(a){F(a,"",5)}function m(a){F(a,"",5,null,"immediate")}function n(a){F(a,"",31)}function o(a){F(a,"",98)}function p(a,b){F(a,b,7)}function q(a,b){F(a,b,55)}function r(a,b){F(a,b,17)}function s(a,b){F(a,b,25)}function t(a,b){F(a,b,115)}function u(a,b){F(a,b,8)}function v(a,b){F(a,b,22)}function w(a,b){F(a,b,27)}function x(a,b){F(a,b,0)}function y(a,b){F(a,(a=b)!=null?a:"",89)}function z(a,b){F(a,(a=b)!=null?a:"",89,null,"immediate")}function A(a,b){F(a,b,60)}function B(a,b){F(a,b,90)}function C(a,b){F(a,b,144)}function D(a,b,c){F(a,b,c)}function E(a,b,c){F(a,b,c,null,"immediate")}function F(a,b,d,e,f){var g=a+"|"+b;e!=null&&(g=g+"|"+e);if(h[g])return;f==="immediate"?c("Qe2JsExposureFalcoEvent").logImmediately(function(){return{universe:a,unit_id:b,unit_type:d,param:e}}):f==="critical"?c("Qe2JsExposureFalcoEvent").logCritical(function(){return{universe:a,unit_id:b,unit_type:d,param:e}}):c("Qe2JsExposureFalcoEvent").log(function(){return{universe:a,unit_id:b,unit_type:d,param:e}});h[g]=!0}g.logExposureForUser=a;g.logExposureForUserImmediately=b;g.logExposureForIGUser=d;g.logExposureForIGUserImmediately=e;g.logExposureForIGWebCookie=f;g.logExposureForIGWebCookieImmediately=i;g.logExposureForIGWebCookieCritical=j;g.logExposureForEmail=k;g.logExposureForDatr=l;g.logExposureForDatrImmediately=m;g.logExposureForOculusLoggedOut=n;g.logExposureForOculusLoggedOutCookieID=o;g.logExposureForPage=p;g.logExposureForPaymentAccountID=q;g.logExposureForBusiness=r;g.logExposureForGroup=s;g.logExposureForPhabricatorDiff=t;g.logExposureForPhoneNumber=u;g.logExposureForScimCompanyID=v;g.logExposureForAnalyticsEntityID=w;g.logExposureForAdAccountID=x;g.logExposureForActingAccount=y;g.logExposureForActingAccountImmediately=z;g.logExposureForMixedUserAndPage=A;g.logExposureForCommerceMerchantSettings=B;g.logExposureForShopifyApplicationInstallationID=C;g.logExposure=D;g.logExposureImmediately=E}),98);
__d("IntlCLDRNumberType01",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("getContextualParent",["ge"],(function(a,b,c,d,e,f,g){function a(a,b){b===void 0&&(b=!1);var d=!1;a=a;do{if(a instanceof Element){var e=a.getAttribute("data-ownerid");if(e){a=c("ge")(e);d=!0;continue}}a=a.parentNode}while(b&&a&&!d);return a}g["default"]=a}),98);